version: 0.2

env:
  variables:
    SOLUTION_FILE: "src\\sample-eval.sln"
    PACKAGE_LOCATION: "publish"

phases:
  install:
    runtime-versions:
      dotnet: 4.8

  pre_build:
    commands:
      - nuget restore $env:SOLUTION_FILE

  build:
    commands:
      - |
        & msbuild $env:SOLUTION_FILE `
        /p:Configuration=Release `
        /p:DeployOnBuild=true `
        /p:WebPublishMethod=Package `
        /p:PackageAsSingleFile=false `
        /p:SkipInvalidConfigurations=true `
        /p:PackageLocation="$env:PACKAGE_LOCATION" `
        /verbosity:detailed
      - tree '.\src\sample-eval\'
      - Get-ChildItem -Path '.\src\sample-eval\'  -Recurse -Force -Filter "*.zip"

artifacts:
  files:
    - src\sample-eval\$env:PACKAGE_LOCATION\**\*
  name: sample-eval
  discard-paths: no

cache:
  paths:
    - 'C:\Users\ContainerAdministrator\.nuget\packages\**\*'
