version: 0.2

env:
  variables:
    SOLUTION_FILE: "src/sample-eval.sln"
    PACKAGE_LOCATION: "src/sample-eval/publish"

phases:
  install:
    runtime-versions:
      dotnet: 4.8
    commands:
      -   choco install visualstudio2019buildtools --package-parameters "--add Microsoft.VisualStudio.Workload.WebBuildTools --quiet --norestart"

  pre_build:
    commands:
      - nuget restore $env:SOLUTION_FILE

  build:
    commands:
      - |
        & "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\MSBuild.exe" $env:SOLUTION_FILE `
        /p:Configuration=Release `
        /p:DeployOnBuild=true `
        /p:WebPublishMethod=Package `
        /p:PackageAsSingleFile=true `
        /p:SkipInvalidConfigurations=true `
        /p:PackageLocation="$env:PACKAGE_LOCATION" `
        /verbosity:detailed

  post_build:
    commands:
      - |
        if (Test-Path "$env:PACKAGE_LOCATION\sample-eval.zip") {
          aws s3 cp "$env:PACKAGE_LOCATION\sample-eval.zip" s3://dotnet-sample-github/sample-eval.zip
        } else {
          Write-Host "Build artifact not found. Skipping S3 upload."
          exit 1
        }

artifacts:
  files:
    - $env:PACKAGE_LOCATION\sample-eval.zip
  name: dotnet-app
  discard-paths: yes

cache:
  paths:
    - 'C:\Users\ContainerAdministrator\.nuget\packages\**\*'