name: Build and Deploy .NET Framework 4.8 Web Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up NuGet
        uses: nuget/setup-nuget@v1

      - name: Restore NuGet packages
        run: nuget restore src/sample-eval.sln

      - name: Install Visual Studio Build Tools (with Web Build Tools)
        run: |
          choco install visualstudio2019buildtools --package-parameters "--add Microsoft.VisualStudio.Workload.WebBuildTools --quiet --norestart"

      - name: Build the solution
        run: |
          "& 'C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\MSBuild.exe' 'src/sample-eval.sln' /p:Configuration=Release"
        shell: pwsh

      - name: Zip published output
        run: |
          Compress-Archive -Path src\sample-eval\bin\Release\* -DestinationPath dotnet-app.zip
        shell: pwsh

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dotnet-app
          path: dotnet-app.zip
